language: node_js
node_js: node
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: XVrJwmn2RJEfWPcqhc+OuH/GCb0BHmshhZOF5RkBaMCP2P0ysKgxsXiNFADfwrzmzNif6xNYUks7JJ9WmDTlZP61t3JYYfddn9rgIR/+xIffjyx22d2HSMk4Bqfw2/Kysqhv15B5q0vPvgxN77u9a6ScrN4fqu6ipQlxBMRKl1fNHCX8PWNt4/cjhgbx3Ar5AXNezz/KmtPE02An7QB2WQX+bug8byCN8FEr5VnAKLVpI7cf5Wup/Hx9FJwRyzNiNmnLHQOrF1RyTl1A7nCvPBM1cw0fbUrpkqJWWVADXtfr8HlFd2pTso33vsdBQXQYQCT3M7JWk3XGTHtZtM1gxqg3OdOJ0Ut3oDNrubxduIKFIu8YHzN45JmGKm6LEK1FZ/p0yb9CJPWq3jhY3pHcrt5a6v+uBLeziiLKlEuZOhuq1ZbCdOvV0rRTksSy5LK/dW02lfneRJd9CYnZZfhwg6yPUaQcm1TdDHgb07H4JwpoX3kn2+iuC8EDJvd5CTnaRwFOyxAfeP6pk9pzu1L6MEkqJmQ8/6qT8TN/w2ED8VRn8WrJ4SJMGY4F3bGzOsq1jtan53vcMi/ddFyluBTqIPb95Yub5ebTVEZcgIoeR3V2STxuSnKLPXg7XUAn87UloK3Bd8uoguiN1iOP1NtS5DoJYVWTtBw1Auloj+lfVM8=
  app: hex-clothes
  on:
    repo: Saitama2016/hex-clothes
