language: node_js
node_js: node
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  app: hex-clothes
  api_key:
    secure: CEozSpAz56Zx2qs0Fs6Yxw/n3XJRh7ZjZExz2PK0e3vb2/AFF7LyiOELddsjhKO6Ylxf7kJQZLDi2TFOUmxChxaR41jjBXK0ou+W6c0b7j4sBZeuiJk2FnPtt1Po48DNfLLbc/MYOg9uHOaO1knGbWlGwd55y3x5Hx+ZqUN01dPMACMrBb9qFtBz8ZkPdzwfrsHCT7AWY8vpxdBOEGsPdLI4zq6Dvyxz2gUS5Uv0OvzUnJXM9E6GgTzcep2HYlrZspolTZyrXoDO4beN/DNbwIN3GhVg5VtOEIeDTG0fR72UH7kptkWs5oHWTfqfgmy401o18J7NSORV1pEcmuczV1Ok29T1MLEtFdx40j/BUgLhX7TxBm6zPIAPxnoIy58bKEwbR1dWhwGhZPfQSRB2Cd6HTHmz7l7H8PMGx3WQ4RtfwHj/Uchl994LHVu3dAIiOOMryF5I4yc5rXRmhNQRzOQUONKrw+Cwh+0z6AAn8//3IG6NHrk7ESewPXkpNAn4UPizAzi+ngpU8e2rqPLRjekN6mMSbwsXP17IcT6aX2ZpY+fSEODEgCd737leM17RxncFM0zhte4HHCBArPSsJj9W70DDeDvBWI87DhtYnB0ruw7U+PhYH4atNzy/+GCFqrY0+L6K91+gjiN7Wq2tYj3EFMg82f7NtXhcp57CDcU=
  on:
    repo: Saitama2016/hex-clothes