language: node_js
node_js: node
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: amOTFZKyeLbKRDs4hxpVcSOoYShxVYngDKJgB76v4qXso0cUv0iqoSptevY0eu/6AU/2mhVt0vslCz3kYfTvKaK5cERILbo+B0oQZg4QUuyIUU2s3mwhNV4hHk5t7CAKrEUQiNaOikWYMATZNg8e2UoqZQl8+6pQuDOo+zXbDjJieFzsDUCLJvfEI3/4zRbBWBAN4YsBOFlQUayy10LS6nflXZK9SL3tDhZEmWBlJNHQxhvUaKX5DfleWRnmA/sbdAo0gKMa800GkEny3Qhpk5n46kz9us5H2dNZekS9K/QzVw4PMaoaJzd+ggs7mBT957w3ba0hZ2z+ee0NY7uCl64gV30IfO66k05TkfRhANTH2fe2FfDDmKzyI6HvkR9cnKA4pxtQuRhsh4XjhlstanIiK6rIe6Cfq2DrYOvkGXMNyNG4Gvaumx/Qcp4jh2Pe1gqAZmJREHwPhwHrISC2+KoTTvONqLMC7a0bqrwhQw0rTsIgy8KuqvqLx334Q1o7Kblty3l2Bq9pcdUUMecKcjoCpwN2SJu4na6L8kzKa2HNc472XeDVPJWhlAi1XL4kay8eIrPg12609rZN3fyUCTyYQNhwmYdJhA5WEd0faQbPf0tI53a5x+iNZHF9BaDvEs/DiUt7gyW1Y54CBCszuY/bIv+s7AuPjJ4ZQvm6Sco=
  app: hex-clothes
  on:
    repo: Saitama2016/hex-clothes